services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: workflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d workflow_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workflow.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev

  backend:
    image: python:3.11-slim
    working_dir: /app
    command: sh -c "pip install -r server/requirements.txt && uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./server:/app/server
      - ./server/requirements.txt:/app/server/requirements.txt:ro
      - .:/app  # Mount repo root for alembic access
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/workflow_db
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:18-alpine
    working_dir: /app/client
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./client:/app/client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  postgres_data:
  pgadmin_data:

