"""add edges table

Revision ID: cf36a89223d4
Revises: 2c1f6be35854
Create Date: 2025-09-17 22:38:51.012787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf36a89223d4'
down_revision = '2c1f6be35854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('from_node_id', sa.String(), nullable=False),
    sa.Column('from_port', sa.String(), nullable=False),
    sa.Column('to_node_id', sa.String(), nullable=False),
    sa.Column('to_port', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edges_from_node', 'edges', ['from_node_id'], unique=False)
    op.create_index('idx_edges_to_node', 'edges', ['to_node_id'], unique=False)
    op.create_index('idx_edges_workflow', 'edges', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_edges_workflow', table_name='edges')
    op.drop_index('idx_edges_to_node', table_name='edges')
    op.drop_index('idx_edges_from_node', table_name='edges')
    op.drop_table('edges')
    # ### end Alembic commands ###
